version: "3"
services:
  selenium:
    image: selenium/standalone-chrome

  webserver:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 81:80
    tty: true

  database:
    image: postgres:latest
    volumes:
      - ensof_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    healthcheck:
      test: pg_isready -U postgres
    ports:
      - '5431:5432'
    networks:
      default:
        aliases:
          - postgres

  api:
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
    build:
      context: ./api
      dockerfile: ./Dockerfile
      args:
        RAILS_ENV: ${RAILS_ENV}
        RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    environment:
      - SELENIUM_REMOTE_HOST=selenium
    volumes:
      - ./api:/api
    ports:
      - "3000:3000"
      - "43447:43447"
    depends_on:
      - database
      - webserver
      - selenium
    tty: true
    stdin_open: true

volumes:
  bundle_cache:
  ensof_postgres:
